sudo: required
services:
  - docker

before_install:
  - docker build -t darkoohrid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true darkoohrid/react-test npm test -- --coverage

after_success:
  - docker build -t darkoohrid/multi-client ./client
  - docker build -t darkoohrid/multi-nginx ./nginx
  - docker build -t darkoohrid/multi-server ./server
  - docker build -t darkoohrid/multi-server ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push darkoohrid/multi-client
  - docker push darkoohrid/multi-nginx
  - docker push darkoohrid/multi-server
  - docker push darkoohrid/multi-worker